### PR TITLE
perf: Concurrently recurse readDir

### PR DESCRIPTION
**Pull request by keegancsmith**
Doing serial ReadDirs when recursing is currently the slowest common operation
that is done by Sourcegraph. This is a simple concurrent version which spawns a
goroutine per recursive call.

### CODE REVIEW

**Comment by keegancsmith** [comment]
This is a very simple implementation, and in repos with directories that have a large number of child directories we may want to limit concurrency. Ideally we would have a batch interface to filesystem operations, since the largest overhead for these operations is git loading it's data-structures into memory, etc:

```
[~/go/src/src.sourcegraph.com/sourcegraph] [git:perf-repotree]
keegan@cliche $ time { for x in *; do git ls-tree origin/master $x; done } > /dev/null

real    0m0.250s
user    0m0.076s
sys     0m0.143s
[~/go/src/src.sourcegraph.com/sourcegraph] [git:perf-repotree]
keegan@cliche $ time git ls-tree origin/master * > /dev/null

real    0m0.006s
user    0m0.002s
sys     0m0.003s
```

Given this is a simplistic implementation and will also conflict with @beyang's open PR #36 I am happy to change this implementation / take over #36.

**Comment by shurcooL** [comment]
I agree that limiting concurrency would be quite critical here. In a directory with 3 subdirectories it will spawn 3 goroutines, but if there are 1000+ subdirectories, it will spawn 1000+ goroutines, each trying to read filesystem. That can become very problematic (running out of open file descriptors, or general system slowness/instability).

Can you elaborate on the difference of:

```
$ time { for x in *; do git ls-tree origin/master $x; done } > /dev/null
$ time git ls-tree origin/master * > /dev/null
```

And how it relates to the changes in this PR, or proposed other changes?

**Comment by keegancsmith** [comment]
The timing example shows the massive difference between using the current naive interface we have, and using batching. ie the difference of telling git up front what directories to do ls-tree on, vs telling git each time. If we had batching a simple bread first search would do this without any recursion / concurrency + be more performant.

**Comment by keegancsmith** [comment]
I have merged these changes into #36.

**Pull request closed without merging**
